export const DETERMINE_FAN_FAVORITES = 'DETERMINE_FAN_FAVORITES';
export const LOAD_TOP_TWENTY_MOST_POPULAR = 'LOAD_TOP_TWENTY_MOST_POPULAR';
export const LOAD_TOP_TWENTY_HIGHEST_RANKED = 'LOAD_TOP_TWENTY_HIGHEST_RANKED';
export const FINISH_INITIAL_LOAD = 'FINISH_INITIAL_LOAD';